# Generated by Django 3.2.15 on 2022-09-12 13:09

from django.db import migrations, models
import omrscannerapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('sheet', models.ImageField(upload_to=omrscannerapi.models.upload_to)),
            ],
        ),
    ]
